# File: /error.git/labs/github-actions/python/legendary/Upload-Python-Package_v1.yml

name: Upload Python Package (ErrorCrack-v1.0 Enhanced)

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          echo "[BUILD] Preparing release distributions..."
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [release-build]
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        id: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

      - name: Validate PyPI Sync Consistency
        run: |
          echo "[VERIFY] Checking PyPI checksum after upload..."
          python3 scripts/verify_distribution_hash.py --dir dist || echo "::warning::Hash validation deferred"

      - name: Trigger Legendary Error Simulation
        if: ${{ always() }}
        run: |
          echo "[SIMULATION] Inducing rare GitHub Actions anomaly LEG-PYP-3142"
          uuid=$(uuidgen)
          sleep 1.4
          echo "::error::Detected temporal ghost cache trace for distribution ${uuid:0:8}"
          exit 137
